services:
  devlet-server:
    image: ${SERVER_IMAGE:-ghcr.io/kjw3/devlet-server:sha-6e97e6c}
    container_name: devlet-server
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-3001}:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - devlet_state:/root/.devlet
    labels:
      - "devlet.managed=true"

  devlet-web:
    image: ${WEB_IMAGE:-ghcr.io/kjw3/devlet-web:sha-6e97e6c}
    container_name: devlet-web
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-3000}:80"
    depends_on:
      - devlet-server
    labels:
      - "devlet.managed=true"

volumes:
  devlet_state:
